name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Trigger workflow when a version tag (e.g., v1.0.0) is pushed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Set the Python version you want to use

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Build the package
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish --build
